### PR TITLE
Feat/#53 styling

### PR DESCRIPTION
**Pull request by ciaranschutte**
In this PR I've taken a delicate hand and applied subtle changes in appearance.
Some highlights, though not literally, include the following: 
- bolding a font (bold font!)
- fixing an arrow direction (what goes up must come down)
- spacing a div (far out man)

### CODE REVIEW

**Comment by joneubank** [comment]
Where your descriptions at?

**Comment by ciaranschutte** [comment]
@joneubank that was the quickest reply ever

**Comment by joneubank** [comment]
Quickest descriptions ever written too. 0 seconds!

**Comment by joneubank** [comment]
I guess I'll just compare to the ticket, is all good 😄

**Comment by ciaranschutte** [comment]
@joneubank description updated

**Pull request merged**
