### PR TITLE
Release Updates - DACO, Download, and Molecular Data Submission Docs

### PR DESCRIPTION
**Pull request by rosibaj**
- [ ] Point to new DACO docs
- [ ] Fix download URLS 
- [ ] Update Molecular Data Submission docs with edits

### CODE REVIEW

**Review by ciaranschutte — DISMISSED** [review]

**Comment by ciaranschutte** [comment]
@rosibaj conflicts from somewhere. did you pull the latest ?

**Comment by blabadi** [comment]
there is a conflict for some reason but otherwise lgtm

**Comment by rosibaj** [comment]
@ciaranschutte  I am not quite sure what you mean.  I reviewed the conflicts, and I dont quite understand why they exist.  

I `did not` squash and merge according to instructions from Dusan. 

just wanted to release "https://github.com/icgc-argo/argo-docs/pull/404" <-- the changes made here.  As you have approved, do I need to resolve the conflicts in the github web editor?

**Comment by ciaranschutte** [comment]
@rosibaj there are quite a few conflicts to resolve in the web editor. I'm trying to see why there are conflicts. Might be a quicker way.

**Comment by ciaranschutte** [comment]
@blabadi Is the only reason for a conflict here because latest `develop` was not worked on somewhere?
We're not version incrementing so there's no `master => develop` merging that could be missed.

**Comment by blabadi** [comment]
> @blabadi Is the only reason for a conflict here because latest `develop` was not worked on somewhere?
> We're not version incrementing so there's no `master => develop` merging that could be missed.

yeah these conflicts mean that at some point master was changed and those commits were not synced to develop. and now that we are pushing from develop to master on these specific files.

**Comment by ciaranschutte** [comment]
@blabadi gotcha. so for @rosibaj best to resolve conflicts in the web editor, or should I resolve the conflicts locally and force push to `master`?

**Comment by blabadi** [comment]
> @blabadi gotcha. so for @rosibaj best to resolve conflicts in the web editor, or should I resolve the conflicts locally and force push to `master`?

check out the develop branch locally and pull from master into develop, resolve the conflicts then push back to develop, this PR will get updated

**Comment by ciaranschutte** [comment]
@rosibaj can you double check this looks ok to you with the updated `develop` branch please?

**Review by blabadi — APPROVED** [review]

**Pull request merged**
